export const SEARCH_MOVIE_BY_USER   = 'SEARCH_MOVIE_BY_USER';
export const LEAVE_SEARCH_PAGE      = 'LEAVE_SEARCH_PAGE';
export const LEAVE_PAGE_FOR_AUTH    = 'LEAVE_PAGE_FOR_AUTH';

export const SEARCH_MOVIES_REQUEST  = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS  = 'SEARCH_MOVIES_SUCCESS';
export const CURRENT_MOVIE_REQUEST  = 'CURRENT_MOVIE_REQUEST';
export const CURRENT_MOVIE_SUCCESS  = 'CURRENT_MOVIE_SUCCESS';
export const SIMILAR_MOVIES_REQUEST = 'SIMILAR_MOVIES_REQUEST';
export const SIMILAR_MOVIES_SUCCESS = 'SIMILAR_MOVIES_SUCCESS';
export const REC_MOVIES_REQUEST     = 'REC_MOVIES_REQUEST';
export const REC_MOVIES_SUCCESS     = 'REC_MOVIES_SUCCESS';

export const AUTH_REQUEST           = 'AUTH_REQUEST';
export const AUTH_SUCCESS           = 'AUTH_SUCCESS';
export const AUTH_FAILURE           = 'AUTH_FAILURE';